model_name: uvcom
enc_layers: 3
dec_layers: 3
num_queries: 30
n_txt_mu: 5
n_visual_mu: 30
sim_loss_coef: 1
neg_loss_coef: 0.5
lr_gamma: 0.1
neg_choose_epoch: 80
lr_drop: 100
em_iter: 5
cross_fusion: False