seed: 2023
device: 'cuda'
num_workers: 4

lr: 0.0001
lr_drop: 400
wd: 0.0001
n_epoch: 200
max_es_cnt: 200
bsz: 32
eval_bsz: 100
grad_clip: 0.1
max_q_l: 32
max_v_l: 75
max_windows: 5
clip_length: 1
eval_epoch_interval: 1

position_embedding: "sine"
enc_layers: 2
dec_layers: 2
dim_feedforward: 1024
hidden_dim: 256
input_dropout: 0.5
dropout: 0.1
nheads: 8
num_queries: 10

n_input_proj: 2
saliency_margin: 0.2
span_loss_type: "l1"
set_cost_span: 10
set_cost_giou: 1
set_cost_class: 4
span_loss_coef: 10
giou_loss_coef: 1
label_loss_coef: 4
eos_coef: 0.1
lw_saliency: 1

ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log
eval_split_name: val
aux_loss: True

model_ema: False
ema_decay: 0.9
results_dir: results