dset_name: tacos
clip_length: 2
train_path: data/tacos/tacos_train_release.jsonl
eval_path: data/tacos/tacos_test_release.jsonl
max_v_l: -1
max_q_l: 100
eval_bsz: 32

lw_saliency: 4
lr: 0.0002
lr_drop: 40