dset_name: youtube_highlight
clip_length: 1
train_path: data/youtube_highlight/youtube_highlight_train_release.jsonl
eval_path: data/youtube_highlight/youtube_highlight_val_release.jsonl
max_q_l: 100
max_v_l: 1000
bsz: 4
seed: 2018
lr: 0.0002
lr_drop: 2000
n_epoch: 1000
lw_saliency: 4